### ISSUE TITLE
DeleteById -endpointtien korjaus

### ISSUE THREAD

**Issue by koskinene** [Bjorn-Eric/TicketGuru#101]
- [x] Event
- [x] Ticket
- [x] Venue

Edellisessä sprintissä havaittiin testauksissa, että jostain syystä delete -metodit eivät toimi ja palauttavat 500 -koodin. Näiden bugien selvittäminen ja korjaus, että deletet toimisivat taas. Tehdäänkö näihin suoraan poistot vai soft deletet?

**Comment by sirkian** [comment]
d11ce4ffdb8efff5e5c3cbd7783aecb1ad582bb3 korjasi ticketin deleten, muut oli korjaantunu ihan vaan levättyään yön yli
