### ISSUE TITLE
Rajapinta tapahtumapaikan muokkaamiselle (PUT)

### ISSUE THREAD

**Issue by sirkian** [Bjorn-Eric/TicketGuru#64]
Web-pakettiin, VenueRestController.java-luokkaan (jos ei ole jo, lisää) tarvittava toiminnallisuus. 

Voitaisiin pyrkiä noudattamaan niitä kurssimatskuissa suositeltuja endpoint-käytäntöjä ja muutenki mahollisimman kuvaavia nimiä metodeille.

ps. muistakaa kirjotella kommentteja koodiin, niitä vaadittiin siinä projektiohjeessa.

_ympäripyöree selitys johtuu siitä, että aion copypastee tän kaikkii näihi kerralla, kyssärit joko alas tai teamssissa_ 😄

**Comment by koskinene** [comment]
67d63c7
